name: Lint

on: [push, pull_request]

jobs:
  lint:
    if: github.repository_owner == 'pytorch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.7.0
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'
      - name: Install lintrunner
        run: pip install lintrunner==0.12.7
      - name: Run lintrunner
        run: lintrunner -a
